### PR TITLE
Silence periodic console messages from Review Cache

### PR DESCRIPTION
**Pull request by bashenk**
Very minor thing, but I prefer to keep the console free of extraneous logging.

Proposed change silences the periodic console messages that the Review Cache would trigger whenever `fetch_new_reviews` is called with `disable_popup` set to true.

### CODE REVIEW

**Review by lupomikti — CHANGES_REQUESTED** [review]
Do you think you could make it so this silent setting is actually something that can be set on the `window.review_cache` object such that changing its value in the console would change the mode of operation (silent vs not silent)?

E.g. I would be able to type `window.review_cache.silent = false;` into the console to restore the current behavior.

**Comment by bashenk** [comment]
That certainly would be possible.
I'll work on something when I get a bit of free time. Though I imagine it'll end up something like what I'm doing with `silenceWarnings` in the Turbo Events library, where the user preference wouldn't get truly "saved", though in this case the default would be `true`.

**Comment by lupomikti** [comment]
That sounds good. I wasn't thinking it would be saved either, that is, when I input that line in the console it would be effective only until the page refreshes (and the script has to be injected again). So a default of `true` and a way to set it to `false` via the console for temporary purposes is ideal.

**Review by lupomikti — APPROVED** [review]
Awesome, this all looks good to me.

**Comment by Kumirei** [comment]
Thanks, the both of you :heart:

**Pull request merged**
