### PR TITLE
reorder.user.ts: Fix streak counter

### PR DESCRIPTION
**Pull request by pektinasen**

### CODE REVIEW

**Comment by Kumirei** [comment]
Under which circumstances is `passed` true while `action` is not `pass`?

**Comment by pektinasen** [comment]
When I inspected the `details` object, there was no property passed. 
For me the counter didn't go up at all.

**Comment by Kumirei** [comment]
Oh, I wonder if it doesn't exist for lessons. Is that what you were testing with?

**Comment by pektinasen** [comment]
No, it was for reviews.

**Comment by pektinasen** [comment]
Is it still working for you?
I can check later with a clean browser again. Was using FF with all my extensions and adblockers.

**Comment by Kumirei** [comment]
I was still seeing the passed property, but after disabling all my script it's gone. I guess WK must have changed it but one of the scripts is perpetuating the old format. I'll get this merged, thanks :)

**Comment by Kumirei** [comment]
Omega, Fast Vocab Breakdown, and the standalone Review Answer Streak, have all been updated on Greasyfork (and GitHub)

**Pull request merged**
