### PR TITLE
Add Omega feature: Lesson batch size changing

### PR DESCRIPTION
**Pull request by lupomikti**
Adds the ability to change the lesson batch size from Omega settings and on the lesson page via Queue Manipulator's `lessonBatchSize` variable. When changed on the lesson page it refreshes the queue to immediately grab lessons of the new size.

I'm still rather new to scripting, and in particular I don't believe UI to be a point I have down well, so the UI to change the batch size on the lesson page may not be in the best spot or have the best styling and thus would require some additional attention. But despite that the feature works as intended.

I also reused the display UI setting for the preset dropdown instead of making a separate display setting for it, but that may want to be done in the future in case someone wants the ability to change batch size quickly but not the ability to switch presets from the lesson page (say because they don't want to reorder at all, only modify batch size).

If you're looking for a specific use case where this feature makes things a lot easier, see my latest comment in the Reorder Omega community thread.

Oh, and, I have no clue if I did this in the right way, but `npm install` would not work until I updated the `peerDependencies` of typedoc to include 4.8.x; if everything works fine on your system this commit isn't really needed but I'm too new at this to know if it's possible to make a pull request with specific commits.

### CODE REVIEW

**Comment by Kumirei** [comment]
@lupomikti I made some changes before merging the request
- Updated styling to match the preset dropdown
- Removed the "Set" button in favor of updating on (debounced) change
- Added a default disabled setting for whether to show the batch input

**Comment by lupomikti** [comment]
It looks like the batch size div is still using the `display_selection` setting instead of the newly made `display_batch_size` setting. Edit: ah, nevermind, I see it's being handled with the body attribute. So removing or changing that line in the interface setup function is a matter of cleanup, not functionality.

**Comment by Kumirei** [comment]
Ah, thanks for pointing that out. I hadn't seen that there. I'll get that cleaned up

**Comment by lupomikti** [comment]
I happened to be looking at Omega again due to looking into stuff with Queue Manipulator, and I noticed something that I missed when making this feature because I hadn't looked at the internals of Queue Manipulator.

We don't need to call `refresh()` after setting batch size in the `onchange` handler for the batch size input because the setter for `lessonBatchSize` in Queue Manipulator calls `requestApplyManipulationsToLessonQueue(false)`; so unless we have reason to suspect that Queue Manipulator's choice to not recompute the queue from the original unaltered queue when setting this variable has consequences we don't want and that it would be better to refresh, which calls the same method with `recomputeQueue` set to `true`, that part of the `onchange` handler can be removed.

Additionally, while looking at this, I realized that the call to `refresh()` in the `onchange` handler for the preset dropdown also shouldn't be needed because we save the settings right before it, and the settings `onsave` function itself calls `refresh()`. So every time the dropdown is changed, it seems like `refresh()` is called twice.

**Pull request merged**
