### PR TITLE
* wanikani reorder omega - add sort type and level preset

### PR DESCRIPTION
**Pull request by aaarrti**
Hi @Kumirei, 

I've been using your "Reorder Omega" plugin for Wanikani recently, and I've been lacking the functionality to sort radical, kanji, vocabulary and keep the level ordering at the same time, so I've decided to add this feature!

### CODE REVIEW

**Comment by Kumirei** [comment]
Thanks for the PR! Always appreciate it when someone takes their time to help me improve my scripts.

However, unless I am missing something I think you can already achieve this by just using two sequential sorts. When you sort, the relative order of items with the same value is preserved, so if you were to first sort by level and then type, it should end up being sorted predominantly by type, and then by level within types. And vice versa, of course, if you sort by type then level.

**Comment by Kumirei** [comment]
It might be a good idea to add a pre-defined preset which does this, to make it clearer to users that the relative order is preserved between sorts

**Comment by aaarrti** [comment]
> Thanks for the PR! Always appreciate it when someone takes their time to help me improve my scripts.
> 
> However, unless I am missing something I think you can already achieve this by just using two sequential sorts. When you sort, the relative order of items with the same value is preserved, so if you were to first sort by level and then type, it should end up being sorted predominantly by type, and then by level within types. And vice versa, of course, if you sort by type then level.

Hi, 
tbh the idea of just using two sorts sequentially had never crossed my mind 🤦
I will look into your suggestion.

**Comment by aaarrti** [comment]
> It might be a good idea to add a pre-defined preset which does this, to make it clearer to users that the relative order is preserved between sorts

Hi @Kumirei, you were right, two sequential sorts do the job. So, I've added a preset with sorts items like this:

- level 1
  - radicals 
  - kanji 
  - vocabulary 
- level 2
  - radicals 
  - kanji 
  - vocabulary 
  
- level ...

**Review by Kumirei — APPROVED** [review]
Looks good to me. Thanks for adding that preset!
I hope to get this merged and published tonight

**Comment by Kumirei** [comment]
Merged. Bumped the version and published. Thank you!

**Pull request merged**
